no message
peg0129/menta_repository pull request #1
Opened 2020-07-03 07:47 UTC by peg0129

2020-07-04 01:07 UTC, youtakanke requested changes

2020-07-04 01:07 UTC, youtakanke commented on index.html
>            targetX = ++targetX; //1pxずつ加算（style当てる訳じゃないから整数1でOK）
こちらを  
`targetX++` のみにしてください。

2020-07-06 05:38 UTC, youtakanke approved these changes

2020-07-06 12:09 UTC, peg0129 commented
circle move right motion end.

2020-07-06 13:20 UTC, merged